Replace words for rbenv
s/rbenv/ndkenv/g
s/RBENV/NDKENV/g
s/ruby/ndk/g
s/Ruby/NDK/g
s/RUBY/NDK/g

diff --git a/libexec/ndkenv b/libexec/ndkenv
--- a/libexec/ndkenv
+++ b/libexec/ndkenv
@@ -3,18 +3,18 @@ set -e
 export -n CDPATH
 
 if [ "$1" = "--debug" ]; then
-  export RBENV_DEBUG=1
+  export NDKENV_DEBUG=1
   shift
 fi
 
-if [ -n "$RBENV_DEBUG" ]; then
+if [ -n "$NDKENV_DEBUG" ]; then
   export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
   set -x
 fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
-  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  echo "ndkenv: cannot find readlink - are you missing GNU coreutils?" >&2
   exit 1
 fi
 
@@ -36,39 +36,39 @@ abs_dirname() {
   cd "$cwd"
 }
 
-if [ -z "${RBENV_ROOT}" ]; then
-  RBENV_ROOT="${HOME}/.rbenv"
+if [ -z "${NDKENV_ROOT}" ]; then
+  NDKENV_ROOT="${HOME}/.ndkenv"
 else
-  RBENV_ROOT="${RBENV_ROOT%/}"
+  NDKENV_ROOT="${NDKENV_ROOT%/}"
 fi
-export RBENV_ROOT
+export NDKENV_ROOT
 
-if [ -z "${RBENV_DIR}" ]; then
-  RBENV_DIR="$(pwd)"
+if [ -z "${NDKENV_DIR}" ]; then
+  NDKENV_DIR="$(pwd)"
 else
-  cd "$RBENV_DIR" 2>/dev/null || {
-    echo "rbenv: cannot change working directory to \`$RBENV_DIR'"
+  cd "$NDKENV_DIR" 2>/dev/null || {
+    echo "ndkenv: cannot change working directory to \`$NDKENV_DIR'"
     exit 1
   } >&2
-  RBENV_DIR="$(pwd)"
+  NDKENV_DIR="$(pwd)"
   cd "$OLDPWD"
 fi
-export RBENV_DIR
+export NDKENV_DIR
 
 
 shopt -s nullglob
 
 bin_path="$(abs_dirname "$0")"
-for plugin_bin in "${RBENV_ROOT}/plugins/"*/bin; do
+for plugin_bin in "${NDKENV_ROOT}/plugins/"*/bin; do
   bin_path="${bin_path}:${plugin_bin}"
 done
 export PATH="${bin_path}:${PATH}"
 
-hook_path="${RBENV_HOOK_PATH}:${RBENV_ROOT}/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"
-for plugin_hook in "${RBENV_ROOT}/plugins/"*/etc/rbenv.d; do
+hook_path="${NDKENV_HOOK_PATH}:${NDKENV_ROOT}/ndkenv.d:/usr/local/etc/ndkenv.d:/etc/ndkenv.d:/usr/lib/ndkenv/hooks"
+for plugin_hook in "${NDKENV_ROOT}/plugins/"*/etc/ndkenv.d; do
   hook_path="${hook_path}:${plugin_hook}"
 done
-export RBENV_HOOK_PATH="$hook_path"
+export NDKENV_HOOK_PATH="$hook_path"
 
 shopt -u nullglob
 
@@ -76,15 +76,15 @@ shopt -u nullglob
 command="$1"
 case "$command" in
 "" | "-h" | "--help" )
-  echo -e "$(rbenv---version)\n$(rbenv-help)" >&2
+  echo -e "$(ndkenv---version)\n$(ndkenv-help)" >&2
   ;;
 "-v" )
-  exec rbenv---version
+  exec ndkenv---version
   ;;
 * )
-  command_path="$(command -v "rbenv-$command" || true)"
+  command_path="$(command -v "ndkenv-$command" || true)"
   if [ -z "$command_path" ]; then
-    echo "rbenv: no such command \`$command'" >&2
+    echo "ndkenv: no such command \`$command'" >&2
     exit 1
   fi
 
diff --git a/libexec/ndkenv-hooks b/libexec/ndkenv-hooks
--- a/libexec/ndkenv-hooks
+++ b/libexec/ndkenv-hooks
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
-# Summary: List hook scripts for a given rbenv command
-# Usage: rbenv hooks <command>
+# Summary: List hook scripts for a given ndkenv command
+# Usage: ndkenv hooks <command>
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$NDKENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide ndkenv completions
 if [ "$1" = "--complete" ]; then
   echo exec
   echo rehash
@@ -13,15 +13,15 @@ if [ "$1" = "--complete" ]; then
   exit
 fi
 
-RBENV_COMMAND="$1"
-if [ -z "$RBENV_COMMAND" ]; then
-  rbenv-help --usage hooks >&2
+NDKENV_COMMAND="$1"
+if [ -z "$NDKENV_COMMAND" ]; then
+  ndkenv-help --usage hooks >&2
   exit 1
 fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
-  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  echo "ndkenv: cannot find readlink - are you missing GNU coreutils?" >&2
   exit 1
 fi
 
@@ -43,11 +43,11 @@ realpath() {
   cd "$cwd"
 }
 
-IFS=: hook_paths=($RBENV_HOOK_PATH)
+IFS=: hook_paths=($NDKENV_HOOK_PATH)
 
 shopt -s nullglob
 for path in "${hook_paths[@]}"; do
-  for script in "$path/$RBENV_COMMAND"/*.bash; do
+  for script in "$path/$NDKENV_COMMAND"/*.bash; do
     echo $(realpath $script)
   done
 done
diff --git a/libexec/ndkenv-init b/libexec/ndkenv-init
--- a/libexec/ndkenv-init
+++ b/libexec/ndkenv-init
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# Summary: Configure the shell environment for rbenv
-# Usage: eval "$(rbenv init - [--no-rehash] [<shell>])"
+# Summary: Configure the shell environment for ndkenv
+# Usage: eval "$(ndkenv init - [--no-rehash] [<shell>])"
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$NDKENV_DEBUG" ] && set -x
 
 print=""
 no_rehash=""
@@ -30,7 +30,7 @@ fi
 
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
-  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  echo "ndkenv: cannot find readlink - are you missing GNU coreutils?" >&2
   exit 1
 fi
 
@@ -73,15 +73,15 @@ if [ -z "$print" ]; then
     ;;
   esac
 
-  { echo "# Load rbenv automatically by adding"
+  { echo "# Load ndkenv automatically by adding"
     echo "# the following to ${profile}:"
     echo
     case "$shell" in
     fish )
-      echo 'status --is-interactive; and . (rbenv init -|psub)'
+      echo 'status --is-interactive; and . (ndkenv init -|psub)'
       ;;
     * )
-      echo 'eval "$(rbenv init -)"'
+      echo 'eval "$(ndkenv init -)"'
       ;;
     esac
     echo
@@ -90,29 +90,29 @@ if [ -z "$print" ]; then
   exit 1
 fi
 
-mkdir -p "${RBENV_ROOT}/"{shims,versions}
+mkdir -p "${NDKENV_ROOT}/"{shims,versions}
 
-if [[ ":${PATH}:" != *:"${RBENV_ROOT}/shims":* ]]; then
+if [[ ":${PATH}:" != *:"${NDKENV_ROOT}/shims":* ]]; then
   case "$shell" in
   fish )
-    echo "setenv PATH '${RBENV_ROOT}/shims' \$PATH"
+    echo "setenv PATH '${NDKENV_ROOT}/shims' \$PATH"
   ;;
   * )
-    echo 'export PATH="'${RBENV_ROOT}'/shims:${PATH}"'
+    echo 'export PATH="'${NDKENV_ROOT}'/shims:${PATH}"'
   ;;
   esac
 fi
 
 case "$shell" in
 fish )
-  echo "setenv RBENV_SHELL $shell"
+  echo "setenv NDKENV_SHELL $shell"
 ;;
 * )
-  echo "export RBENV_SHELL=$shell"
+  echo "export NDKENV_SHELL=$shell"
 ;;
 esac
 
-completion="${root}/completions/rbenv.${shell}"
+completion="${root}/completions/ndkenv.${shell}"
 if [ -r "$completion" ]; then
   case "$shell" in
   fish ) echo ". '$completion'" ;;
@@ -121,35 +121,35 @@ if [ -r "$completion" ]; then
 fi
 
 if [ -z "$no_rehash" ]; then
-  echo 'rbenv rehash 2>/dev/null'
+  echo 'ndkenv rehash 2>/dev/null'
 fi
 
-commands=(`rbenv-commands --sh`)
+commands=(`ndkenv-commands --sh`)
 case "$shell" in
 fish )
   cat <<EOS
-function rbenv
+function ndkenv
   set command \$argv[1]
   set -e argv[1]
 
   switch "\$command"
   case ${commands[*]}
-    eval (rbenv "sh-\$command" \$argv)
+    eval (ndkenv "sh-\$command" \$argv)
   case '*'
-    command rbenv "\$command" \$argv
+    command ndkenv "\$command" \$argv
   end
 end
 EOS
   ;;
 ksh )
   cat <<EOS
-function rbenv {
+function ndkenv {
   typeset command
 EOS
   ;;
 * )
   cat <<EOS
-rbenv() {
+ndkenv() {
   local command
 EOS
   ;;
@@ -165,9 +165,9 @@ cat <<EOS
 
   case "\$command" in
   ${commands[*]})
-    eval "\`rbenv "sh-\$command" "\$@"\`";;
+    eval "\`ndkenv "sh-\$command" "\$@"\`";;
   *)
-    command rbenv "\$command" "\$@";;
+    command ndkenv "\$command" "\$@";;
   esac
 }
 EOS
diff --git a/libexec/ndkenv-prefix b/libexec/ndkenv-prefix
--- a/libexec/ndkenv-prefix
+++ b/libexec/ndkenv-prefix
@@ -1,41 +1,41 @@
 #!/usr/bin/env bash
-# Summary: Display prefix for a Ruby version
-# Usage: rbenv prefix [<version>]
+# Summary: Display prefix for a NDK version
+# Usage: ndkenv prefix [<version>]
 #
-# Displays the directory where a Ruby version is installed. If no
-# version is given, `rbenv prefix' displays the location of the
+# Displays the directory where a NDK version is installed. If no
+# version is given, `ndkenv prefix' displays the location of the
 # currently selected version.
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$NDKENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide ndkenv completions
 if [ "$1" = "--complete" ]; then
   echo system
-  exec rbenv-versions --bare
+  exec ndkenv-versions --bare
 fi
 
 if [ -n "$1" ]; then
-  export RBENV_VERSION="$1"
-elif [ -z "$RBENV_VERSION" ]; then
-  RBENV_VERSION="$(rbenv-version-name)"
+  export NDKENV_VERSION="$1"
+elif [ -z "$NDKENV_VERSION" ]; then
+  NDKENV_VERSION="$(ndkenv-version-name)"
 fi
 
-if [ "$RBENV_VERSION" = "system" ]; then
-  if RUBY_PATH="$(rbenv-which ruby 2>/dev/null)"; then
-    RUBY_PATH="${RUBY_PATH%/*}"
-    echo "${RUBY_PATH%/bin}"
+if [ "$NDKENV_VERSION" = "system" ]; then
+  if NDK_PATH="$(ndkenv-which ndk 2>/dev/null)"; then
+    NDK_PATH="${NDK_PATH%/*}"
+    echo "${NDK_PATH%/bin}"
     exit
   else
-    echo "rbenv: system version not found in PATH" >&2
+    echo "ndkenv: system version not found in PATH" >&2
     exit 1
   fi
 fi
 
-RBENV_PREFIX_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}"
-if [ ! -d "$RBENV_PREFIX_PATH" ]; then
-  echo "rbenv: version \`${RBENV_VERSION}' not installed" >&2
+NDKENV_PREFIX_PATH="${NDKENV_ROOT}/versions/${NDKENV_VERSION}"
+if [ ! -d "$NDKENV_PREFIX_PATH" ]; then
+  echo "ndkenv: version \`${NDKENV_VERSION}' not installed" >&2
   exit 1
 fi
 
-echo "$RBENV_PREFIX_PATH"
+echo "$NDKENV_PREFIX_PATH"
diff --git a/libexec/ndkenv-which b/libexec/ndkenv-which
--- a/libexec/ndkenv-which
+++ b/libexec/ndkenv-which
@@ -2,17 +2,17 @@
 #
 # Summary: Display the full path to an executable
 #
-# Usage: rbenv which <command>
+# Usage: ndkenv which <command>
 #
-# Displays the full path to the executable that rbenv will invoke when
+# Displays the full path to the executable that ndkenv will invoke when
 # you run the given command.
 
 set -e
-[ -n "$RBENV_DEBUG" ] && set -x
+[ -n "$NDKENV_DEBUG" ] && set -x
 
-# Provide rbenv completions
+# Provide ndkenv completions
 if [ "$1" = "--complete" ]; then
-  exec rbenv shims --short
+  exec ndkenv shims --short
 fi
 
 expand_path() {
@@ -48,37 +48,37 @@ remove_from_path() {
   echo "${result%:}"
 }
 
-RBENV_VERSION="$(rbenv-version-name)"
-RBENV_COMMAND="$1"
+NDKENV_VERSION="$(ndkenv-version-name)"
+NDKENV_COMMAND="$1"
 
-if [ -z "$RBENV_COMMAND" ]; then
-  rbenv-help --usage which >&2
+if [ -z "$NDKENV_COMMAND" ]; then
+  ndkenv-help --usage which >&2
   exit 1
 fi
 
-if [ "$RBENV_VERSION" = "system" ]; then
-  PATH="$(remove_from_path "${RBENV_ROOT}/shims")"
-  RBENV_COMMAND_PATH="$(command -v "$RBENV_COMMAND" || true)"
+if [ "$NDKENV_VERSION" = "system" ]; then
+  PATH="$(remove_from_path "${NDKENV_ROOT}/shims")"
+  NDKENV_COMMAND_PATH="$(command -v "$NDKENV_COMMAND" || true)"
 else
-  RBENV_COMMAND_PATH="${RBENV_ROOT}/versions/${RBENV_VERSION}/bin/${RBENV_COMMAND}"
+  NDKENV_COMMAND_PATH="${NDKENV_ROOT}/versions/${NDKENV_VERSION}/bin/${NDKENV_COMMAND}"
 fi
 
 OLDIFS="$IFS"
-IFS=$'\n' scripts=(`rbenv-hooks which`)
+IFS=$'\n' scripts=(`ndkenv-hooks which`)
 IFS="$OLDIFS"
 for script in "${scripts[@]}"; do
   source "$script"
 done
 
-if [ -x "$RBENV_COMMAND_PATH" ]; then
-  echo "$RBENV_COMMAND_PATH"
+if [ -x "$NDKENV_COMMAND_PATH" ]; then
+  echo "$NDKENV_COMMAND_PATH"
 else
-  echo "rbenv: $RBENV_COMMAND: command not found" >&2
+  echo "ndkenv: $NDKENV_COMMAND: command not found" >&2
 
-  versions="$(rbenv-whence "$RBENV_COMMAND" || true)"
+  versions="$(ndkenv-whence "$NDKENV_COMMAND" || true)"
   if [ -n "$versions" ]; then
     { echo
-      echo "The \`$1' command exists in these Ruby versions:"
+      echo "The \`$1' command exists in these NDK versions:"
       echo "$versions" | sed 's/^/  /g'
       echo
     } >&2
