Show full version when install to excepting root

diff --git a/libexec/ndkenv---version b/libexec/ndkenv---version
--- a/libexec/ndkenv---version
+++ b/libexec/ndkenv---version
@@ -14,7 +14,31 @@ set -e
 
 version="0.4.0"
 
-if cd "$NDKENV_ROOT" 2>/dev/null; then
+READLINK=$(type -p greadlink readlink | head -1)
+if [ -z "$READLINK" ]; then
+  echo "ndkenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
+
+resolve_link() {
+  $READLINK "$1"
+}
+
+abs_dirname() {
+  local cwd="$(pwd)"
+  local path="$1"
+
+  while [ -n "$path" ]; do
+    cd "${path%/*}"
+    local name="${path##*/}"
+    path="$(resolve_link "$name" || true)"
+  done
+
+  pwd
+  cd "$cwd"
+}
+
+if cd $(abs_dirname "$0") 2>/dev/null; then
   git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
   git_revision="${git_revision#v}"
 fi
